//! Integration tests for diffguard-analytics component handoffs.
//!
//! These tests exercise the seams between analytics functions:
//! 1. `fingerprint_for_finding` → `baseline_from_receipt` (fingerprint feeds into baseline)
//! 2. `baseline_from_receipt` → `merge_false_positive_baselines` (baseline feeds into merge)
//! 3. `merge_false_positive_baselines` → `false_positive_fingerprint_set` (merged baseline feeds into lookup set)
//! 4. Full pipeline: receipt → fingerprint → baseline → merge → fingerprint_set
//!
//! The `#[must_use]` attribute on `merge_false_positive_baselines` means callers MUST capture
//! the return value. These integration tests verify that capturing the return value produces
//! correct end-to-end behavior.

use diffguard_analytics::{
    FALSE_POSITIVE_BASELINE_SCHEMA_V1, FalsePositiveBaseline, FalsePositiveEntry, TrendHistory,
    append_trend_run, baseline_from_receipt, false_positive_fingerprint_set,
    fingerprint_for_finding, merge_false_positive_baselines, normalize_false_positive_baseline,
    summarize_trend_history, trend_run_from_receipt,
};
use diffguard_types::{
    CheckReceipt, DiffMeta, Finding, Scope, Severity, ToolMeta, Verdict, VerdictCounts,
    VerdictStatus,
};

// ============================================================================
// Helper Factories
// ============================================================================

fn make_finding(rule_id: &str, path: &str, line: u32, match_text: &str) -> Finding {
    Finding {
        rule_id: rule_id.to_string(),
        severity: Severity::Error,
        message: "Test message".to_string(),
        path: path.to_string(),
        line,
        column: Some(1),
        match_text: match_text.to_string(),
        snippet: format!("line {} {}", line, match_text),
    }
}

fn make_receipt(findings: Vec<Finding>) -> CheckReceipt {
    CheckReceipt {
        schema: "diffguard.check.v1".to_string(),
        tool: ToolMeta {
            name: "diffguard".to_string(),
            version: "0.2.0".to_string(),
        },
        diff: DiffMeta {
            base: "origin/main".to_string(),
            head: "HEAD".to_string(),
            context_lines: 3,
            scope: Scope::Added,
            files_scanned: 1,
            lines_scanned: 10,
        },
        findings,
        verdict: Verdict {
            status: VerdictStatus::Fail,
            counts: VerdictCounts {
                info: 0,
                warn: 0,
                error: 1,
                suppressed: 0,
            },
            reasons: vec![],
        },
        timing: None,
    }
}

// ============================================================================
// Hand-off 1: fingerprint_for_finding → baseline_from_receipt
// ============================================================================

/// Integration test: fingerprint_from_finding is used correctly by baseline_from_receipt.
/// The fingerprint generated by `fingerprint_for_finding` must appear as the fingerprint
/// field in entries created by `baseline_from_receipt`.
#[test]
fn integration_fingerprint_feeds_into_baseline_from_receipt() {
    let finding = make_finding("rust.no_unwrap", "src/lib.rs", 42, "unwrap()");
    let expected_fp = fingerprint_for_finding(&finding);

    let receipt = make_receipt(vec![finding]);
    let baseline = baseline_from_receipt(&receipt);

    assert_eq!(baseline.entries.len(), 1);
    assert_eq!(baseline.entries[0].fingerprint, expected_fp);
    assert_eq!(baseline.entries[0].rule_id, "rust.no_unwrap");
    assert_eq!(baseline.entries[0].path, "src/lib.rs");
    assert_eq!(baseline.entries[0].line, 42);
}

/// Integration test: multiple findings each produce unique fingerprints in baseline.
#[test]
fn integration_multiple_fingerprints_in_baseline() {
    let findings = vec![
        make_finding("rust.no_unwrap", "src/lib.rs", 10, "unwrap()"),
        make_finding("rust.no_debug", "src/main.rs", 20, "dbg!()"),
        make_finding("rust.no_expect", "src/lib.rs", 30, "expect()"),
    ];
    let receipt = make_receipt(findings);
    let baseline = baseline_from_receipt(&receipt);

    let fingerprints: Vec<_> = baseline.entries.iter().map(|e| &e.fingerprint).collect();
    assert_eq!(fingerprints.len(), 3);
    // All fingerprints should be unique
    let mut sorted = fingerprints.clone();
    sorted.sort();
    sorted.dedup();
    assert_eq!(sorted.len(), 3, "All fingerprints should be unique");
}

// ============================================================================
// Hand-off 2: baseline_from_receipt → merge_false_positive_baselines
// ============================================================================

/// Integration test: baseline_from_receipt output is a valid input to merge_false_positive_baselines.
/// This tests the pipeline: receipt → baseline → merge.
#[test]
fn integration_baseline_from_receipt_feeds_into_merge() {
    let finding = make_finding("rust.no_unwrap", "src/lib.rs", 42, "unwrap()");
    let receipt = make_receipt(vec![finding]);

    let generated = baseline_from_receipt(&receipt);

    // Empty base + generated = normalized generated
    let empty = FalsePositiveBaseline::default();
    let merged = merge_false_positive_baselines(&empty, &generated);

    assert_eq!(merged.entries.len(), 1);
    assert_eq!(merged.schema, FALSE_POSITIVE_BASELINE_SCHEMA_V1);
    assert_eq!(merged.entries[0].rule_id, "rust.no_unwrap");
}

/// Integration test: two baselines from receipts merge correctly.
#[test]
fn integration_two_receipt_baselines_merge_correctly() {
    let findings1 = vec![make_finding("rust.no_unwrap", "src/lib.rs", 10, "unwrap()")];
    let findings2 = vec![make_finding("rust.no_debug", "src/main.rs", 20, "dbg!()")];

    let receipt1 = make_receipt(findings1);
    let receipt2 = make_receipt(findings2);

    let baseline1 = baseline_from_receipt(&receipt1);
    let baseline2 = baseline_from_receipt(&receipt2);

    // Merge: base=baseline1, incoming=baseline2
    let merged = merge_false_positive_baselines(&baseline1, &baseline2);

    assert_eq!(merged.entries.len(), 2);
    let rules: Vec<_> = merged.entries.iter().map(|e| e.rule_id.as_str()).collect();
    assert!(rules.contains(&"rust.no_unwrap"));
    assert!(rules.contains(&"rust.no_debug"));
}

// ============================================================================
// Hand-off 3: merge_false_positive_baselines → false_positive_fingerprint_set
// ============================================================================

/// Integration test: merge_false_positive_baselines output is a valid input to false_positive_fingerprint_set.
/// This tests the pipeline: merge → fingerprint_set.
#[test]
fn integration_merged_baseline_feeds_into_fingerprint_set() {
    let base = FalsePositiveBaseline {
        schema: FALSE_POSITIVE_BASELINE_SCHEMA_V1.to_string(),
        entries: vec![FalsePositiveEntry {
            fingerprint: "fp_base".to_string(),
            rule_id: "rule.base".to_string(),
            path: "base.rs".to_string(),
            line: 1,
            note: Some("base note".to_string()),
        }],
    };
    let incoming = FalsePositiveBaseline {
        schema: FALSE_POSITIVE_BASELINE_SCHEMA_V1.to_string(),
        entries: vec![FalsePositiveEntry {
            fingerprint: "fp_incoming".to_string(),
            rule_id: "rule.incoming".to_string(),
            path: "incoming.rs".to_string(),
            line: 2,
            note: None,
        }],
    };

    let merged = merge_false_positive_baselines(&base, &incoming);
    let fp_set = false_positive_fingerprint_set(&merged);

    assert_eq!(fp_set.len(), 2);
    assert!(fp_set.contains("fp_base"));
    assert!(fp_set.contains("fp_incoming"));
}

// ============================================================================
// Full Pipeline Tests: receipt → fingerprint → baseline → merge → fingerprint_set
// ============================================================================

/// Integration test: complete pipeline from CheckReceipt to fingerprint lookup set.
/// This exercises: receipt → baseline_from_receipt → merge_false_positive_baselines → false_positive_fingerprint_set
#[test]
fn integration_full_pipeline_receipt_to_fingerprint_set() {
    // Step 1: Create two receipts with findings
    let findings1 = vec![make_finding("rust.no_unwrap", "src/lib.rs", 10, "unwrap()")];
    let findings2 = vec![make_finding("rust.no_debug", "src/main.rs", 20, "dbg!()")];

    let receipt1 = make_receipt(findings1);
    let receipt2 = make_receipt(findings2);

    // Step 2: Build baselines from receipts
    let baseline1 = baseline_from_receipt(&receipt1);
    let baseline2 = baseline_from_receipt(&receipt2);

    // Step 3: Merge baselines (base=existing baseline, incoming=new check)
    let merged = merge_false_positive_baselines(&baseline1, &baseline2);

    // Step 4: Extract fingerprint set for fast lookup
    let fp_set = false_positive_fingerprint_set(&merged);

    // Verify the full pipeline worked
    assert_eq!(fp_set.len(), 2);
    assert!(fp_set.contains(&baseline1.entries[0].fingerprint));
    assert!(fp_set.contains(&baseline2.entries[0].fingerprint));
}

/// Integration test: full pipeline with an existing baseline (simulating --write-false-positive-baseline flow).
/// This simulates how diffguard main binary uses these functions:
/// - Generate baseline from current check receipt
/// - Load existing baseline from disk (or use empty)
/// - Merge existing + generated
/// - Extract fingerprint set for filtering
#[test]
fn integration_existing_plus_generated_baseline_pipeline() {
    // Simulate: existing baseline from previous runs (with a manually curated note)
    let mut existing = FalsePositiveBaseline::default();
    existing.entries.push(FalsePositiveEntry {
        fingerprint: "existing_fp".to_string(),
        rule_id: "old.rule".to_string(),
        path: "old.rs".to_string(),
        line: 5,
        note: Some("intentionally suppressed".to_string()),
    });

    // Current check run generates new findings
    let new_findings = vec![
        make_finding("rust.no_unwrap", "src/lib.rs", 10, "unwrap()"),
        make_finding("rust.no_debug", "src/main.rs", 20, "dbg!()"),
    ];
    let receipt = make_receipt(new_findings);
    let generated = baseline_from_receipt(&receipt);

    // Merge: existing (base) + generated (incoming)
    let merged = merge_false_positive_baselines(&existing, &generated);

    // Extract fingerprint set
    let fp_set = false_positive_fingerprint_set(&merged);

    // Should have 3 total fingerprints
    assert_eq!(fp_set.len(), 3);
    assert!(fp_set.contains("existing_fp"));

    // Verify the existing note was preserved (merge strategy: base fills empty fields)
    let existing_entry = merged
        .entries
        .iter()
        .find(|e| e.fingerprint == "existing_fp")
        .expect("existing_fp should exist");
    assert_eq!(
        existing_entry.note.as_deref(),
        Some("intentionally suppressed")
    );
}

/// Integration test: full pipeline is deterministic (same inputs → same outputs).
#[test]
fn integration_full_pipeline_is_deterministic() {
    let findings = vec![make_finding("rust.no_unwrap", "src/lib.rs", 42, "unwrap()")];
    let receipt = make_receipt(findings);

    let baseline = baseline_from_receipt(&receipt);
    let merged1 = merge_false_positive_baselines(&baseline, &FalsePositiveBaseline::default());
    let merged2 = merge_false_positive_baselines(&baseline, &FalsePositiveBaseline::default());

    let set1 = false_positive_fingerprint_set(&merged1);
    let set2 = false_positive_fingerprint_set(&merged2);

    assert_eq!(set1, set2);
}

// ============================================================================
// Trend History Integration Tests
// ============================================================================

/// Integration test: append_trend_run + summarize_trend_history pipeline.
#[test]
fn integration_trend_append_and_summarize() {
    let findings = vec![make_finding("rust.no_unwrap", "src/lib.rs", 42, "unwrap()")];
    let receipt = make_receipt(findings);

    let run1 = trend_run_from_receipt(
        &receipt,
        "2026-01-01T00:00:00Z",
        "2026-01-01T00:00:01Z",
        1000,
    );
    let mut run2 = trend_run_from_receipt(
        &receipt,
        "2026-01-02T00:00:00Z",
        "2026-01-02T00:00:01Z",
        1000,
    );
    run2.findings = 5;
    run2.counts.error = 5;

    let history = TrendHistory::default();
    let history = append_trend_run(history, run1, None);
    let history = append_trend_run(history, run2, None);

    let summary = summarize_trend_history(&history);

    assert_eq!(summary.run_count, 2);
    assert_eq!(summary.total_findings, 6); // 1 + 5
    let delta = summary.delta_from_previous.expect("should have delta");
    assert_eq!(delta.findings, 4); // 5 - 1
}

/// Integration test: trend pipeline with max_runs trimming.
#[test]
fn integration_trend_with_max_runs_trimming() {
    let findings = vec![make_finding("rust.no_unwrap", "src/lib.rs", 42, "unwrap()")];
    let receipt = make_receipt(findings);

    let history = TrendHistory::default();
    let history = append_trend_run(
        history,
        trend_run_from_receipt(
            &receipt,
            "2026-01-01T00:00:00Z",
            "2026-01-01T00:00:01Z",
            1000,
        ),
        Some(3),
    );
    let history = append_trend_run(
        history,
        trend_run_from_receipt(
            &receipt,
            "2026-01-02T00:00:00Z",
            "2026-01-02T00:00:01Z",
            1000,
        ),
        Some(3),
    );
    let history = append_trend_run(
        history,
        trend_run_from_receipt(
            &receipt,
            "2026-01-03T00:00:00Z",
            "2026-01-03T00:00:01Z",
            1000,
        ),
        Some(3),
    );
    let history = append_trend_run(
        history,
        trend_run_from_receipt(
            &receipt,
            "2026-01-04T00:00:00Z",
            "2026-01-04T00:00:01Z",
            1000,
        ),
        Some(3),
    );

    // Should be trimmed to 3 (oldest dropped)
    assert_eq!(history.runs.len(), 3);
    // Oldest should be from 2026-01-02 (2026-01-01 dropped)
    assert_eq!(history.runs[0].started_at, "2026-01-02T00:00:00Z");
}

// ============================================================================
// Error Handling Integration
// ============================================================================

/// Integration test: normalize_false_positive_baseline cleans up before merge.
#[test]
fn integration_normalize_before_merge() {
    // Create a baseline with unsorted entries and duplicates (simulating corrupted/manual baseline)
    let dirty = FalsePositiveBaseline {
        schema: String::new(), // Missing schema
        entries: vec![
            FalsePositiveEntry {
                fingerprint: "zzz".to_string(),
                rule_id: "z.rule".to_string(),
                path: "z.rs".to_string(),
                line: 3,
                note: None,
            },
            FalsePositiveEntry {
                fingerprint: "aaa".to_string(),
                rule_id: "a.rule".to_string(),
                path: "a.rs".to_string(),
                line: 1,
                note: None,
            },
            // Duplicate fingerprint
            FalsePositiveEntry {
                fingerprint: "aaa".to_string(),
                rule_id: "a.rule".to_string(),
                path: "a.rs".to_string(),
                line: 1,
                note: None,
            },
        ],
    };

    // Normalize first, then merge
    let normalized = normalize_false_positive_baseline(dirty);
    let merged = merge_false_positive_baselines(&normalized, &FalsePositiveBaseline::default());

    // Should be sorted, deduplicated, and have correct schema
    assert_eq!(merged.schema, FALSE_POSITIVE_BASELINE_SCHEMA_V1);
    assert_eq!(merged.entries.len(), 2); // zzz and aaa (aaa was deduplicated)
    assert_eq!(merged.entries[0].fingerprint, "aaa"); // Sorted first
    assert_eq!(merged.entries[1].fingerprint, "zzz"); // Sorted second
}
