//! Property-based tests for diffguard-testkit invariants.
//!
//! These tests verify important invariants that should hold across all generated
//! inputs, not just specific examples. Property tests run hundreds of iterations
//! to find edge cases that example-based tests might miss.
//!
//! Invariants tested:
//! - Roundtrip: serialize → deserialize preserves identity
//! - Bounded: generated values stay within MAX_* limits
//! - Valid: generated patterns are syntactically valid regex/globs
//! - MatchMode: all generated RuleConfigs have match_mode = MatchMode::Any

use diffguard_testkit::arb::{self, MAX_PATHS_PER_RULE, MAX_PATTERNS_PER_RULE};
use diffguard_types::{MatchMode, RuleConfig, Severity};
use proptest::prelude::*;
use proptest::strategy::ValueTree;
use proptest::test_runner::TestRunner;

/// Property: ConfigFile roundtrips through JSON serialization.
///
/// For all generated ConfigFiles, serialize to JSON and deserialize back
/// should produce an identical ConfigFile.
#[test]
fn config_file_roundtrip() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_config_file();

    for _ in 0..50 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        let json = serde_json::to_string(&config).unwrap();
        let parsed: diffguard_types::ConfigFile = serde_json::from_str(&json).unwrap();
        assert_eq!(
            config, parsed,
            "ConfigFile should roundtrip through JSON serialization"
        );
    }
}

/// Property: Generated RuleConfig has match_mode = MatchMode::Any.
///
/// All RuleConfigs generated by arb strategies should use MatchMode::Any
/// (which is the default value). This verifies the fix for default_trait_access lint.
#[test]
fn rule_config_match_mode_is_any() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_rule_config();

    for _ in 0..100 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        assert_eq!(
            config.match_mode,
            MatchMode::Any,
            "Generated RuleConfig should have match_mode = MatchMode::Any"
        );
    }
}

/// Property: Minimal RuleConfig has match_mode = MatchMode::Any.
///
/// Verifies that arb_minimal_rule_config() also produces configs with
/// match_mode = MatchMode::Any.
#[test]
fn minimal_rule_config_match_mode_is_any() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_minimal_rule_config();

    for _ in 0..100 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        assert_eq!(
            config.match_mode,
            MatchMode::Any,
            "Minimal RuleConfig should have match_mode = MatchMode::Any"
        );
    }
}

/// Property: RuleConfig patterns count is bounded.
///
/// For all generated RuleConfigs, patterns.len() should be <= MAX_PATTERNS_PER_RULE.
#[test]
fn rule_config_patterns_bounded() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_rule_config();

    for _ in 0..100 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        assert!(
            config.patterns.len() <= MAX_PATTERNS_PER_RULE,
            "patterns.len() = {} exceeds MAX_PATTERNS_PER_RULE = {}",
            config.patterns.len(),
            MAX_PATTERNS_PER_RULE
        );
    }
}

/// Property: RuleConfig paths count is bounded.
///
/// For all generated RuleConfigs, paths.len() should be <= MAX_PATHS_PER_RULE.
#[test]
fn rule_config_paths_bounded() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_rule_config();

    for _ in 0..100 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        assert!(
            config.paths.len() <= MAX_PATHS_PER_RULE,
            "paths.len() = {} exceeds MAX_PATHS_PER_RULE = {}",
            config.paths.len(),
            MAX_PATHS_PER_RULE
        );
    }
}

/// Property: RuleConfig exclude_paths count is bounded.
///
/// For all generated RuleConfigs, exclude_paths.len() should be <= MAX_PATHS_PER_RULE.
#[test]
fn rule_config_exclude_paths_bounded() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_rule_config();

    for _ in 0..100 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        assert!(
            config.exclude_paths.len() <= MAX_PATHS_PER_RULE,
            "exclude_paths.len() = {} exceeds MAX_PATHS_PER_RULE = {}",
            config.exclude_paths.len(),
            MAX_PATHS_PER_RULE
        );
    }
}

/// Property: MatchMode roundtrips through JSON serialization.
///
/// MatchMode::Any and MatchMode::Absent should roundtrip correctly.
#[test]
fn match_mode_roundtrip() {
    // Test MatchMode::Any
    let json_any = serde_json::to_string(&MatchMode::Any).unwrap();
    let parsed_any: MatchMode = serde_json::from_str(&json_any).unwrap();
    assert_eq!(
        MatchMode::Any,
        parsed_any,
        "MatchMode::Any should roundtrip"
    );

    // Test MatchMode::Absent
    let json_absent = serde_json::to_string(&MatchMode::Absent).unwrap();
    let parsed_absent: MatchMode = serde_json::from_str(&json_absent).unwrap();
    assert_eq!(
        MatchMode::Absent,
        parsed_absent,
        "MatchMode::Absent should roundtrip"
    );

    // Test MatchMode::default() (which is Any)
    let default = MatchMode::default();
    let json_default = serde_json::to_string(&default).unwrap();
    let parsed_default: MatchMode = serde_json::from_str(&json_default).unwrap();
    assert_eq!(
        default, parsed_default,
        "MatchMode::default() should roundtrip"
    );
}

/// Property: RuleConfig ID is non-empty.
#[test]
fn rule_config_id_non_empty() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_rule_config();

    for _ in 0..100 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        assert!(!config.id.is_empty(), "RuleConfig ID should not be empty");
    }
}

/// Property: RuleConfig has at least one pattern.
#[test]
fn rule_config_has_patterns() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_rule_config();

    for _ in 0..100 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        assert!(
            !config.patterns.is_empty(),
            "RuleConfig should have at least one pattern"
        );
    }
}

/// Property: Generated regex patterns are valid regex.
#[test]
fn generated_regex_patterns_are_valid() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_regex_pattern();

    for _ in 0..100 {
        let pattern = strategy.new_tree(&mut runner).unwrap().current();
        assert!(
            regex::Regex::new(&pattern).is_ok(),
            "Generated pattern '{}' should be valid regex",
            pattern
        );
    }
}

/// Property: Generated glob patterns are valid glob.
#[test]
fn generated_glob_patterns_are_valid() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_glob_pattern();

    for _ in 0..100 {
        let pattern = strategy.new_tree(&mut runner).unwrap().current();
        assert!(
            globset::Glob::new(&pattern).is_ok(),
            "Generated glob '{}' should be valid",
            pattern
        );
    }
}

/// Property: ConfigFile with generated rules validates against schema.
#[test]
fn generated_config_file_is_valid() {
    use diffguard_testkit::schema::validate_config_file;

    let mut runner = TestRunner::default();
    let strategy = arb::arb_config_file();

    for _ in 0..50 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        if let Err(e) = validate_config_file(&config) {
            panic!(
                "Generated ConfigFile should validate against schema: {:?}",
                e
            );
        }
    }
}

/// Property: All RuleConfigs in a ConfigFile have non-empty IDs.
#[test]
fn config_file_rules_have_non_empty_ids() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_config_file();

    for _ in 0..50 {
        let config = strategy.new_tree(&mut runner).unwrap().current();
        for (i, rule) in config.rule.iter().enumerate() {
            assert!(
                !rule.id.is_empty(),
                "Rule {} in ConfigFile should have non-empty ID, got empty string",
                i
            );
        }
    }
}

/// Property: Severity roundtrips through JSON serialization.
#[test]
fn severity_roundtrip_property() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_severity();

    for _ in 0..100 {
        let sev = strategy.new_tree(&mut runner).unwrap().current();
        let json = serde_json::to_string(&sev).unwrap();
        let parsed: Severity = serde_json::from_str(&json).unwrap();
        assert_eq!(sev, parsed, "Severity should roundtrip through JSON");
    }
}

/// Property: RuleConfig roundtrips through JSON serialization.
#[test]
fn rule_config_roundtrip() {
    let mut runner = TestRunner::default();
    let strategy = arb::arb_rule_config();

    for _ in 0..100 {
        let rule = strategy.new_tree(&mut runner).unwrap().current();
        let json = serde_json::to_string(&rule).unwrap();
        let parsed: RuleConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(rule, parsed, "RuleConfig should roundtrip through JSON");
    }
}
