//! Focused fuzz target for `evaluate_lines`.
//!
//! This target exercises evaluation logic with arbitrary rule/line inputs and
//! validates core invariants (counts, truncation, scan accounting).

#![no_main]

use arbitrary::Arbitrary;
use libfuzzer_sys::fuzz_target;

use diffguard_domain::{InputLine, compile_rules, evaluate_lines};
use diffguard_types::{RuleConfig, Severity};

/// Structured fuzz input for evaluate_lines fuzzing.
///
/// This input contains arbitrary lines and rules that get fed to `evaluate_lines`
/// to discover edge cases in pattern matching, truncation, and count tracking.
#[derive(Arbitrary, Debug)]
struct FuzzInput {
    /// Input lines to evaluate against the rules.
    lines: Vec<FuzzLine>,
    /// Rule configurations to apply.
    rules: Vec<FuzzRule>,
    /// Maximum number of findings to return (truncation boundary).
    max_findings: u8,
}

/// A single input line to be evaluated.
#[derive(Arbitrary, Debug)]
struct FuzzLine {
    /// File path for the line (used for language detection and glob matching).
    path: String,
    /// Line number in the file.
    line: u32,
    /// Line content to check against rules.
    content: String,
}

/// A fuzz-generated rule configuration.
///
/// Note: This is a simplified version of RuleConfig that only includes
/// the fields that can be directly generated by Arbitrary.
#[derive(Arbitrary, Debug)]
struct FuzzRule {
    /// Rule identifier.
    id: String,
    /// Severity level: 0=info, 1=warn, 2=error.
    severity: u8,
    /// Rule message displayed when the rule matches.
    message: String,
    /// Language filters (e.g., "rust", "python").
    languages: Vec<String>,
    /// Regex patterns to match against lines.
    patterns: Vec<String>,
    /// Path globs to include.
    paths: Vec<String>,
    /// Path globs to exclude.
    exclude_paths: Vec<String>,
    /// Whether to ignore matches in comments.
    ignore_comments: bool,
    /// Whether to ignore matches in strings.
    ignore_strings: bool,
}

impl FuzzRule {
    /// Convert to a RuleConfig for use in `evaluate_lines`.
    ///
    /// Returns None if the rule is invalid:
    /// - Empty patterns (would fail regex compilation)
    /// - Empty id (not useful)
    /// - Patterns longer than 500 chars (could cause compilation timeout)
    fn to_rule_config(&self) -> Option<RuleConfig> {
        if self.id.is_empty() || self.patterns.is_empty() {
            return None;
        }

        if self.patterns.iter().any(|p| p.len() > 500) {
            return None;
        }

        let severity = match self.severity % 3 {
            0 => Severity::Info,
            1 => Severity::Warn,
            _ => Severity::Error,
        };

        Some(RuleConfig {
            id: self.id.clone(),
            description: String::new(),
            severity,
            message: self.message.clone(),
            languages: self.languages.clone(),
            patterns: self.patterns.clone(),
            paths: self.paths.clone(),
            exclude_paths: self.exclude_paths.clone(),
            ignore_comments: self.ignore_comments,
            ignore_strings: self.ignore_strings,
            match_mode: Default::default(),
            multiline: false,
            multiline_window: None,
            context_patterns: vec![],
            context_window: None,
            escalate_patterns: vec![],
            escalate_window: None,
            escalate_to: None,
            depends_on: vec![],
            help: None,
            url: None,
            tags: vec![],
            test_cases: vec![],
        })
    }
}

fuzz_target!(|input: FuzzInput| {
    let rules: Vec<RuleConfig> = input
        .rules
        .iter()
        .filter_map(FuzzRule::to_rule_config)
        .collect();
    if rules.is_empty() {
        return;
    }

    let compiled = match compile_rules(&rules) {
        Ok(rules) => rules,
        Err(_) => return,
    };

    let lines: Vec<InputLine> = input
        .lines
        .iter()
        .take(200)
        .map(|line| InputLine {
            path: line.path.clone(),
            line: line.line,
            content: line.content.clone(),
        })
        .collect();

    let max_findings = usize::from(input.max_findings).clamp(1, 200);
    let eval = evaluate_lines(lines.clone(), &compiled, max_findings);

    assert!(eval.findings.len() <= max_findings);

    let total = eval.counts.info + eval.counts.warn + eval.counts.error;
    assert!(total >= eval.findings.len() as u32);
    assert_eq!(total, eval.findings.len() as u32 + eval.truncated_findings);
    assert_eq!(eval.lines_scanned as usize, lines.len());
});
